### PR TITLE
Lock activeSubs map when accessing it

### LINKED ISSUE #36: Prevent concurrent map writes

### PR DESCRIPTION
**Pull request by kt3k**
This PR use RWLock when accessing pubSubQueues.activeSubs map.

closes #36

### CODE REVIEW

**Comment by kt3k** [comment]
@at-wat @t-asaka 
I added test case `TestMultipleSubscription` which causes `concurrent map writes` fatal error with master branch. This PR fixes that error.

**Comment by kt3k** [comment]
@at-wat 
> activeSubs will be removed if auto-reconnect feature is fully migrated to paho.mqtt's AutoReconnect.
Anyway, it's useful as a short-term workaround.

Question about this. Paho doesn't seem supporting auto subscription of topics when it's reconnected cf. https://github.com/eclipse/paho.mqtt.golang/issues/238

As the comment above suggests, we need to set `CleanSession` option to `false` if we want to skip resubscription by this library. But I guess setting `CleanSession: false` has other (possibly harmful) effects because it keeps all the session information in the broker.

Do you think we should use `CleanSession: false` option?

I think another option is that we keep activeSubs and use them in OnConnect callback to subscribe on each reconnect.

**Comment by at-wat** [comment]
> Do you think we should use CleanSession: false option?

Umm, I'm not sure which is better.
I think I should learn MQTT specification more.

https://docs.aws.amazon.com/iot/latest/developerguide/mqtt-persistent-sessions.html
> When the client reconnects to the persistent session, all subscriptions are reinstated and all stored messages are sent to the client at a maximum rate of 10 messages per second. 

If one of the MQTT client send too many QoS>=1 message during device offline, it may cause a problem.
But, it should be a problem of the usage, since QoS>=1 message is flagged to be definitely delivered.

> Persistent sessions have a default expiry period of 1 hour.

This is good.

**Comment by kt3k** [comment]
OK. Persistent sessions seem supported by aws iot, and have reasonable thresholds for message throughputs. I'll try use it (will remove auto resubscription feature of this lib.)

**Pull request merged**
